[package]
name = "wasm"
version = "0.1.0"
authors = ["togami2864 <tuabobo123@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
serde_json = { version = "1.0.96", default-features = false, features = ["alloc"] }
rmonkey_evaluator = {path = "../rmonkey_evaluator"}
rmonkey_lexer = {path = "../rmonkey_lexer"}
rmonkey_parser = {path = "../rmonkey_parser"}
rmonkey_fmt = {path = "../rmonkey_fmt"}

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
